
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT EQUAL OR QUOTE USERNAME VALUE\n    sql_injection : username condition\n                  | username COMMENT\n    \n  condition : simple_condition\n            | complex_condition\n           \n  \n  username : USERNAME\n            | empty\n  \n  empty :\n  \n  simple_condition : QUOTE COMMENT\n  \n  complex_condition :  QUOTE OR QUOTE VALUE QUOTE EQUAL QUOTE VALUE \n                          | QUOTE OR QUOTE QUOTE EQUAL QUOTE  \n  '
    
_lr_action_items = {'USERNAME':([0,],[3,]),'COMMENT':([0,2,3,4,9,],[-7,6,-5,-6,10,]),'QUOTE':([0,2,3,4,11,12,14,15,18,],[-7,9,-5,-6,12,13,16,17,19,]),'$end':([1,5,6,7,8,10,17,20,],[0,-1,-2,-3,-4,-8,-10,-9,]),'OR':([9,],[11,]),'VALUE':([12,19,],[14,20,]),'EQUAL':([13,16,],[15,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sql_injection':([0,],[1,]),'username':([0,],[2,]),'empty':([0,],[4,]),'condition':([2,],[5,]),'simple_condition':([2,],[7,]),'complex_condition':([2,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sql_injection","S'",1,None,None,None),
  ('sql_injection -> username condition','sql_injection',2,'p_sql_injection','newparser.py',7),
  ('sql_injection -> username COMMENT','sql_injection',2,'p_sql_injection','newparser.py',8),
  ('condition -> simple_condition','condition',1,'p_condition','newparser.py',25),
  ('condition -> complex_condition','condition',1,'p_condition','newparser.py',26),
  ('username -> USERNAME','username',1,'p_username','newparser.py',33),
  ('username -> empty','username',1,'p_username','newparser.py',34),
  ('empty -> <empty>','empty',0,'p_empty','newparser.py',40),
  ('simple_condition -> QUOTE COMMENT','simple_condition',2,'p_simple_condition','newparser.py',46),
  ('complex_condition -> QUOTE OR QUOTE VALUE QUOTE EQUAL QUOTE VALUE','complex_condition',8,'p_complex_condition','newparser.py',52),
  ('complex_condition -> QUOTE OR QUOTE QUOTE EQUAL QUOTE','complex_condition',6,'p_complex_condition','newparser.py',53),
]
